version: 0.1

phases:
  pre_build:
    commands:
      - echo '<settings><servers><server><id>tlist-release-repo</id><username>${env.ACCESS_KEY_ID}</username><password>${env.SECRET_ACCESS_KEY}</password></server><server><id>tlist-snapshot-repo</id><username>${env.ACCESS_KEY_ID}</username><password>${env.SECRET_ACCESS_KEY}</password></server></servers></settings>' > ~/.m2/settings.xml
  build:
    commands:
      - mvn clean deploy